name: toothnet
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.7.1
  - cudatoolkit=11.0
  - tqdm
  - scipy
  - open3d
  - pip
  - pip:
      - wandb
      - trimesh